### ISSUE TITLE
Not working in react native 0.62.2

### ISSUE THREAD

**Issue by mohanasundaramn** [ifsnow/react-native-infinite-flatlist-patch#3]
react-native: 0.62.2
react: 16.11.0
platform: ios

**Comment by mohanasundaramn** [comment]
It would be helpful if you add patch for `react-native: 0.62.2`

**Comment by ifsnow** [comment]
I have no problem in v0.62.2, what is the problem?
Let me know what's wrong and I'll check it out.

**Comment by mohanasundaramn** [comment]
`onEndReached` triggering 2 times in a row

**Comment by ifsnow** [comment]
I think it depends on how it is being used. There are several factors that influence it. For example, the length (height) of the first loaded list. Unfortunately, this patch cannot cover all cases. I guess you need to adjust `onEndReachedThreshold` or change the number of list items that are initially loaded. 

You can try test app. https://github.com/ifsnow/FlatListImprovementTest

Hope the problem is solved.
